baseurl = "http://cameron-c-chapman.github.io/"
languageCode = "en-us"
title = "Cameron Chapman"
theme = "casper"
paginate = 5
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120
[[menu.main]]
name = "Github repos"
pre = "<h3>Follow me</h3>"
url = "https://github.com/Cameron-C-Chapman"
weight = 100
[[menu.main]]
name = "Twitter timeline"
url = "https://twitter.com/cameron_kc"
weight = 101
[params]
author = "Cameron Chapman"
authorlocation = "Kansas City, Missouri, United States"
authorwebsite = "http://cameron-c-chapman.github.io/"
bio = "Full stack developer."
cover = "images/cover_polenord.jpg"
description = "Blogging to help myself learn and share some of what I enjoy to do."
githubName = "Cameron-C-Chapman"
googleAnalyticsUserID = "UA-79101-12"
hideHUGOSupport = false

twitterName = "cameron_kc"
[permalinks]
post = "/:slug/"